---
- name: Gather facts for instances with name {{ ec2_scope }}
  ec2_instance_facts:
    region:  "{{ ec2_region }}"
    filters: "{{ ec2_lb_filters }}"
  register: ec2

- name: Build a list of ec2 instances IDs
  vars:
    ids_to_add: "{{ ec2.instances | map(attribute='instance_id') | list }}"
  set_fact:
    ids_to_add: "{{ ids_to_add }}"

- name: Build the list of instances ID and ports
  vars:
    ids_and_ports: []
  set_fact:
    ids_and_ports: "{{ ids_and_ports +  [ {'Id': item, 'Port': 80} ] }}"
  with_items: "{{ ids_to_add }}"

- name: Add Instances to the load balancer target {{ ec2_lb_target }}
  elb_target_group:
    name: "{{ ec2_lb_target }}"
    protocol: http
    port: "{{ ec2_lb_target_port }}"
    vpc_id: "{{ ec2_vpc }}"
    region:  "{{ ec2_region }}"
    modify_targets: Yes
    state: present
    target_type: instance
    targets: "{{ ids_and_ports }}"